FROM continuumio/miniconda3:4.10.3

COPY .devcontainer/requirement4braingnn.yaml /tmp/conda-tmp/requirement4braingnn.yaml
RUN /opt/conda/bin/conda env create -f /tmp/conda-tmp/requirement4braingnn.yaml
